### PR TITLE
Updated readme for nano & esp32 + deleted unused files

### PR DESCRIPTION
**Pull request by TomasRoj**
Some readme were wrong and they had czech links. I also deleted some mess etc.

### CODE REVIEW

**Review by petrkr — COMMENTED** [review]
The file ` esp32/esp32-07-servo/octopusLAB_ROBOT.h` is used by sketch for pinout. It is not unused here.

I agree there could be some octopuslab library, which will contains this file later.

**Comment by TomasRoj** [comment]
Yes we are working on this library now : https://github.com/TomasRoj/OctopusLab-Library/ I can add you as collaborator if you want.

**Comment by petrkr** [comment]
> Yes we are working on this library now : https://github.com/TomasRoj/OctopusLab-Library/ I can add you as collaborator if you want.

Ok then, but I think remove of that include should be done after library is released, so if someone will clone this example (and commit), it will not fail on "file not found".

**Comment by TomasRoj** [comment]
Ok, How can I put it back?

**Comment by TomasRoj** [comment]
This  .h file I uploaded to the library so users can find it there. I dont think that it will fail with file not found because its in examples folder where it should not be. Examples want only example, no more mysterious files they dont know what they do.

**Comment by petrkr** [comment]
Just tested your fork, example `07-servo`. Also downloaded OctopusLab library by hand. And it failed:

```
/home/petrkr/.arduino15/packages/esp32/tools/xtensa-esp32-elf-gcc/1.22.0-80-g6c4433a-5.2.0/bin/xtensa-esp32-elf-g++ -DESP_PLATFORM "-DMBEDTLS_CONFIG_FILE=\"mbedtls/esp_config.h\"" -DHAVE_CONFIG_H -I/home/petrkr/.arduino15/packages/esp32/hardware/esp32/1.0.1/tools/sdk/include/config -I/home/petrkr/.arduino15/packages/esp32/hardware/esp32/1.0.1/tools/sdk/include/app_trace -I/home/petrkr/.arduino15/packages/esp32/hardware/esp32/1.0.1/tools/sdk/include/app_update -I/home/petrkr/.arduino15/packages/esp32/hardware/esp32/1.0.1/tools/sdk/include/asio -I/home/petrkr/.arduino15/packages/esp32/hardware/esp32/1.0.1/tools/sdk/include/bootloader_support -I/home/petrkr/.arduino15/packages/esp32/hardware/esp32/1.0.1/tools/sdk/include/bt -I/home/petrkr/.arduino15/packages/esp32/hardware/esp32/1.0.1/tools/sdk/include/coap -I/home/petrkr/.arduino15/packages/esp32/hardware/esp32/1.0.1/tools/sdk/include/console -I/home/petrkr/.arduino15/packages/esp32/hardware/esp32/1.0.1/tools/sdk/include/driver -I/home/petrkr/.arduino15/packages/esp32/hardware/esp32/1.0.1/tools/sdk/include/esp-tls -I/home/petrkr/.arduino15/packages/esp32/hardware/esp32/1.0.1/tools/sdk/include/esp32 -I/home/petrkr/.arduino15/packages/esp32/hardware/esp32/1.0.1/tools/sdk/include/esp_adc_cal -I/home/petrkr/.arduino15/packages/esp32/hardware/esp32/1.0.1/tools/sdk/include/esp_event -I/home/petrkr/.arduino15/packages/esp32/hardware/esp32/1.0.1/tools/sdk/include/esp_http_client -I/home/petrkr/.arduino15/packages/esp32/hardware/esp32/1.0.1/tools/sdk/include/esp_http_server -I/home/petrkr/.arduino15/packages/esp32/hardware/esp32/1.0.1/tools/sdk/include/esp_https_ota -I/home/petrkr/.arduino15/packages/esp32/hardware/esp32/1.0.1/tools/sdk/include/esp_https_server -I/home/petrkr/.arduino15/packages/esp32/hardware/esp32/1.0.1/tools/sdk/include/esp_ringbuf -I/home/petrkr/.arduino15/packages/esp32/hardware/esp32/1.0.1/tools/sdk/include/ethernet -I/home/petrkr/.arduino15/packages/esp32/hardware/esp32/1.0.1/tools/sdk/include/expat -I/home/petrkr/.arduino15/packages/esp32/hardware/esp32/1.0.1/tools/sdk/include/fatfs -I/home/petrkr/.arduino15/packages/esp32/hardware/esp32/1.0.1/tools/sdk/include/freemodbus -I/home/petrkr/.arduino15/packages/esp32/hardware/esp32/1.0.1/tools/sdk/include/freertos -I/home/petrkr/.arduino15/packages/esp32/hardware/esp32/1.0.1/tools/sdk/include/heap -I/home/petrkr/.arduino15/packages/esp32/hardware/esp32/1.0.1/tools/sdk/include/idf_test -I/home/petrkr/.arduino15/packages/esp32/hardware/esp32/1.0.1/tools/sdk/include/jsmn -I/home/petrkr/.arduino15/packages/esp32/hardware/esp32/1.0.1/tools/sdk/include/json -I/home/petrkr/.arduino15/packages/esp32/hardware/esp32/1.0.1/tools/sdk/include/libsodium -I/home/petrkr/.arduino15/packages/esp32/hardware/esp32/1.0.1/tools/sdk/include/log -I/home/petrkr/.arduino15/packages/esp32/hardware/esp32/1.0.1/tools/sdk/include/lwip -I/home/petrkr/.arduino15/packages/esp32/hardware/esp32/1.0.1/tools/sdk/include/mbedtls -I/home/petrkr/.arduino15/packages/esp32/hardware/esp32/1.0.1/tools/sdk/include/mdns -I/home/petrkr/.arduino15/packages/esp32/hardware/esp32/1.0.1/tools/sdk/include/micro-ecc -I/home/petrkr/.arduino15/packages/esp32/hardware/esp32/1.0.1/tools/sdk/include/mqtt -I/home/petrkr/.arduino15/packages/esp32/hardware/esp32/1.0.1/tools/sdk/include/newlib -I/home/petrkr/.arduino15/packages/esp32/hardware/esp32/1.0.1/tools/sdk/include/nghttp -I/home/petrkr/.arduino15/packages/esp32/hardware/esp32/1.0.1/tools/sdk/include/nvs_flash -I/home/petrkr/.arduino15/packages/esp32/hardware/esp32/1.0.1/tools/sdk/include/openssl -I/home/petrkr/.arduino15/packages/esp32/hardware/esp32/1.0.1/tools/sdk/include/protobuf-c -I/home/petrkr/.arduino15/packages/esp32/hardware/esp32/1.0.1/tools/sdk/include/protocomm -I/home/petrkr/.arduino15/packages/esp32/hardware/esp32/1.0.1/tools/sdk/include/pthread -I/home/petrkr/.arduino15/packages/esp32/hardware/esp32/1.0.1/tools/sdk/include/sdmmc -I/home/petrkr/.arduino15/packages/esp32/hardware/esp32/1.0.1/tools/sdk/include/smartconfig_ack -I/home/petrkr/.arduino15/packages/esp32/hardware/esp32/1.0.1/tools/sdk/include/soc -I/home/petrkr/.arduino15/packages/esp32/hardware/esp32/1.0.1/tools/sdk/include/spi_flash -I/home/petrkr/.arduino15/packages/esp32/hardware/esp32/1.0.1/tools/sdk/include/spiffs -I/home/petrkr/.arduino15/packages/esp32/hardware/esp32/1.0.1/tools/sdk/include/tcp_transport -I/home/petrkr/.arduino15/packages/esp32/hardware/esp32/1.0.1/tools/sdk/include/tcpip_adapter -I/home/petrkr/.arduino15/packages/esp32/hardware/esp32/1.0.1/tools/sdk/include/ulp -I/home/petrkr/.arduino15/packages/esp32/hardware/esp32/1.0.1/tools/sdk/include/unity -I/home/petrkr/.arduino15/packages/esp32/hardware/esp32/1.0.1/tools/sdk/include/vfs -I/home/petrkr/.arduino15/packages/esp32/hardware/esp32/1.0.1/tools/sdk/include/wear_levelling -I/home/petrkr/.arduino15/packages/esp32/hardware/esp32/1.0.1/tools/sdk/include/wifi_provisioning -I/home/petrkr/.arduino15/packages/esp32/hardware/esp32/1.0.1/tools/sdk/include/wpa_supplicant -I/home/petrkr/.arduino15/packages/esp32/hardware/esp32/1.0.1/tools/sdk/include/xtensa-debug-module -I/home/petrkr/.arduino15/packages/esp32/hardware/esp32/1.0.1/tools/sdk/include/esp32-camera -I/home/petrkr/.arduino15/packages/esp32/hardware/esp32/1.0.1/tools/sdk/include/esp-face -I/home/petrkr/.arduino15/packages/esp32/hardware/esp32/1.0.1/tools/sdk/include/fb_gfx -std=gnu++11 -fno-exceptions -Os -g3 -Wpointer-arith -fexceptions -fstack-protector -ffunction-sections -fdata-sections -fstrict-volatile-bitfields -mlongcalls -nostdlib -w -Wno-error=unused-function -Wno-error=unused-but-set-variable -Wno-error=unused-variable -Wno-error=deprecated-declarations -Wno-unused-parameter -Wno-sign-compare -fno-rtti -c -w -x c++ -E -CC -DF_CPU=240000000L -DARDUINO=10809 -DARDUINO_Node32s -DARDUINO_ARCH_ESP32 "-DARDUINO_BOARD=\"Node32s\"" "-DARDUINO_VARIANT=\"node32s\"" -DESP32 -DCORE_DEBUG_LEVEL=0 -I/home/petrkr/.arduino15/packages/esp32/hardware/esp32/1.0.1/cores/esp32 -I/home/petrkr/.arduino15/packages/esp32/hardware/esp32/1.0.1/variants/node32s /tmp/arduino_build_969157/sketch/esp32-07-servo.ino.cpp -o /dev/null
esp32-07-servo:2:30: error: octopusLAB_ROBOT.h: No such file or directory
 #include "octopusLAB_ROBOT.h"

                              ^
compilation terminated.
exit status 1
octopusLAB_ROBOT.h: No such file or directory
```

**Comment by TomasRoj** [comment]
Ok, sorry I didnt test it this way, How can I put it back?

**Comment by TomasRoj** [comment]
By adding this file we can short time what we need to get this pr merged

**Comment by petrkr** [comment]
First two commits seems to be duplicate of first PR. Maybe u need to rebase your tree to latest merged one.

**Comment by TomasRoj** [comment]
Yes you are right. I never did this so I have no idea how to do it. Can you give me some instructions how to do it? Or are you able to do it?

**Pull request closed without merging**
